# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 23f03621e79a1979e3ea25dcac04b293
  secret_key: d1c2c27d8375a6300a99ec408bfde121
  canvas_page_name: /macrodeckplaces-test/
  callback_url: /
  pretty_errors: true
  set_asset_host_to_callback_url: true

test:
  api_key: d90f27cab1014065a8c90630186b9776
  secret_key: 8564bcd16141d4c650dd4dc55725b291
  canvas_page_name: /macrodeckplaces/
  callback_url: /
  set_asset_host_to_callback_url: true

production:
  api_key: d90f27cab1014065a8c90630186b9776
  secret_key: 8564bcd16141d4c650dd4dc55725b291
  canvas_page_name: /macrodeckplaces/
  callback_url: /
  set_asset_host_to_callback_url: true

