
development:
    key: 23f03621e79a1979e3ea25dcac04b293
    secret: d1c2c27d8375a6300a99ec408bfde121
    canvas_path: /macrodeckplaces-test/
    callback_path: /facebook/
    tunnel:
      username: ziggy
      host: prometheus.poseidonimaging.com
      port: 3000
      local_port: 3000

test:
    key: d90f27cab1014065a8c90630186b9776
    secret: 8564bcd16141d4c650dd4dc55725b291
    canvas_path: /macrodeckplaces/
    callback_path: /facebook/
    tunnel:
      username: ziggy
      host: prometheus.poseidonimaging.com
      port: 3000
      local_port: 3000

production:
    key: d90f27cab1014065a8c90630186b9776
    secret: 8564bcd16141d4c650dd4dc55725b291
    canvas_path: /macrodeckplaces/
    callback_path: /facebook/
    tunnel:
      username: ziggy
      host: prometheus.poseidonimaging.com
      port: 3000
      local_port: 3000
