# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "data_groups", :force => true do |t|
    t.column "groupingtype", :string
    t.column "creator", :string
    t.column "groupingid", :string
    t.column "owner", :string
    t.column "tags", :text
    t.column "parent", :string
    t.column "title", :string
    t.column "description", :text
  end

  create_table "data_items", :force => true do |t|
    t.column "datatype", :string
    t.column "datacreator", :string
    t.column "dataid", :string
    t.column "grouping", :string
    t.column "owner", :string
    t.column "creator", :string
    t.column "creation", :integer
    t.column "tags", :text
    t.column "title", :string
    t.column "description", :text
    t.column "stringdata", :text
    t.column "integerdata", :integer
    t.column "objectdata", :text
    t.column "read_permissions", :string
    t.column "write_permissions", :string
  end

  create_table "group_members", :force => true do |t|
    t.column "groupid", :string
    t.column "userid", :string
    t.column "level", :string
    t.column "isbanned", :boolean
  end

  create_table "groups", :force => true do |t|
    t.column "uuid", :string
    t.column "name", :string
    t.column "displayname", :string
    t.column "creation", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "uuid", :string
    t.column "username", :string
    t.column "password", :string
    t.column "passwordhint", :string
    t.column "secretquestion", :string
    t.column "secretanswer", :string
    t.column "name", :string
    t.column "displayname", :string
    t.column "creation", :integer
    t.column "dob", :date
    t.column "authcode", :string
  end

end
